# NOTE: update this with your service name
service: firmoteka

# Create an optimized package for our functions
package:
  individually: true

useDotenv: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin # Load ..env as environment variables
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  userPoolName: ${self:provider.stage}-${self:service}-user-pool
  usersTableName: ${self:provider.stage}-${self:service}-users
  accountId: 378190466098

functions:
  confirmUserSignup:
    handler: functions/confirm-user-signup.handler
    environment:
      USERS_TABLE: !Ref UsersTable
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt UsersTable.Arn
    events:


resources:
  - ${file(resources/cognito.yml)}
  - ${file(resources/dynamodb.yml)}

