Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.usersTableName}
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: username
          AttributeType: S
        - AttributeName: full_name
          AttributeType: S
        - AttributeName: phone_number
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: company_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: username
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: UserByCompanyIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: company_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: UserByFullNameIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: full_name
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: UserByPhoneIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: phone_number
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: UserByEmailIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: email
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  
  CompaniesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.companiesTableName}
      AttributeDefinitions:
        - AttributeName: pib
          AttributeType: S
        - AttributeName: activity_code
          AttributeType: S
        - AttributeName: short_name
          AttributeType: S
        - AttributeName: activity
          AttributeType: S
        - AttributeName: country
          AttributeType: S
        - AttributeName: est_date
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: pib
          KeyType: HASH
        - AttributeName: activity_code
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: getCompanyByStatus
          KeySchema:
            - AttributeName: pib
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: getCompanyByActivity
          KeySchema:
            - AttributeName: pib
              KeyType: HASH
            - AttributeName: activity
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: getCompanyByEstDate
          KeySchema:
            - AttributeName: pib
              KeyType: HASH
            - AttributeName: est_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: getCompanyByShortName
          KeySchema:
            - AttributeName: pib
              KeyType: HASH
            - AttributeName: short_name
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: getCompanyByCountry
          KeySchema:
            - AttributeName: pib
              KeyType: HASH
            - AttributeName: country
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        